#jdbc.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/db_mybatis?useSSL=false&serverTimezone=UTC
#jdbc.username=root
#jdbc.password=123456
# 服务器配置
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mybatis?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis 映射文件
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml